CC = g++
FLAGS = -std=c++11 -pedantic -Wall -Werror -Wno-sign-compare -Wno-long-long -lm
FILES = lab6.cpp TLongNumber.cpp
PROG = lab6
longNumbers:
	$(CC) $(FLAGS) -o $(PROG).out $(FILES)

clean:
	rm -f *.o longNumbers